name = "Qwen3 32B"
family = "qwen"
release_date = "2024-12-23"
last_updated = "2024-12-23"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-11-08"
tool_call = true
open_weights = true

[cost]
input = 0.29
output = 0.59

[limit]
context = 131_072
output = 40_960

[modalities]
input = ["text"]
output = ["text"]
