name = "claude-sonnet-4-5-20250929"
release_date = "2025-09-30"
last_updated = "2025-09-30"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-03"

[cost]
input = 3.000
output = 15.000

[limit]
context = 200_000
output = 64_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
