name = "claude-3-5-haiku-20241022"
release_date = "2024-10-22"
last_updated = "2024-10-22"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2024-07"

[cost]
input = 0.800
output = 4.000

[limit]
context = 200_000
output = 8_192

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
