name = "gemini-3.1-flash-image-preview"
release_date = "2026-02-27"
last_updated = "2026-02-27"
attachment = true
reasoning = false
temperature = true
tool_call = false
open_weights = false
knowledge = "2025-01"

[cost]
input = 0.500
output = 60.000

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text", "image", "pdf"]
output = ["text", "image"]
