name = "glm-4.6"
release_date = "2025-09-30"
last_updated = "2025-09-30"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-03"

[cost]
input = 0.286
output = 1.142

[limit]
context = 200_000
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
