name = "glm-4.6"
family = "glm"
release_date = "2025-09-30"
last_updated = "2025-09-30"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true
knowledge = "2025-04"

[cost]
input = 0.286
output = 1.142

[limit]
context = 204_800
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
