name = "glm-4.5-x"
family = "glm"
release_date = "2025-07-29"
last_updated = "2025-07-29"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-04"

[cost]
input = 1.143
output = 2.290

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
