name = "gpt-4.1"
family = "gpt"
release_date = "2025-04-14"
last_updated = "2025-04-14"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false
knowledge = "2024-04"

[cost]
input = 2.000
output = 8.000

[limit]
context = 1_047_576
output = 32_768

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
