name = "gpt-5.4-nano-2026-03-17"
release_date = "2026-03-19"
last_updated = "2026-03-19"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = false
knowledge = "2025-08"

[cost]
input = 0.200
output = 1.250

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
