name = "gpt-5-mini"
family = "gpt-mini"
release_date = "2025-08-08"
last_updated = "2025-08-08"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = true
open_weights = false
knowledge = "2024-05-30"

[cost]
input = 0.250
output = 2.000

[limit]
context = 400_000
input = 272_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
