name = "gpt-5-pro"
family = "gpt-pro"
release_date = "2025-10-08"
last_updated = "2025-10-08"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = true
open_weights = false
knowledge = "2024-09-30"

[cost]
input = 15.000
output = 120.000

[limit]
context = 400_000
input = 272_000
output = 272_000

[modalities]
input = ["text", "image"]
output = ["text"]
