name = "gpt-5.4-pro"
family = "gpt-pro"
release_date = "2026-03-05"
last_updated = "2026-03-05"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = false
open_weights = false
knowledge = "2025-08-31"

[cost]
input = 30.000
output = 180.000
cache_read = 0
cache_write = 0

[[cost.tiers]]
tier = { size = 272_000 }
input = 60.000
output = 270.000

[limit]
context = 1_050_000
input = 922_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
