name = "gpt-5.2"
family = "gpt"
release_date = "2025-12-12"
last_updated = "2025-12-12"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = true
open_weights = false
knowledge = "2025-08-31"

[cost]
input = 1.750
output = 14.000

[limit]
context = 400_000
input = 272_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
