name = "grok-4.20-multi-agent-beta-0309"
release_date = "2026-03-16"
last_updated = "2026-03-16"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 2.000
output = 6.000

[limit]
context = 2_000_000
output = 30_000

[modalities]
input = ["text", "image"]
output = ["text"]
