name = "MiniMax-M2.7-highspeed"
release_date = "2026-03-19"
last_updated = "2026-03-19"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.600
output = 4.800

[limit]
context = 204_800
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
