name = "Mistral Small 3.2"
family = "mistral-small"
release_date = "2025-01-31"
last_updated = "2025-01-31"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.50
output = 2.20

[limit]
context = 120000
output = 120000

[modalities]
input = ["text"]
output = ["text"]