name = "MoonshotAI: Kimi Latest"
release_date = "2026-04-27"
last_updated = "2026-05-01"
attachment = true
reasoning = true
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0.74
output = 3.49
cache_read = 0.14

[limit]
context = 262142
output = 262142

[modalities]
input = ["text", "image"]
output = ["text"]
