name = "Qwen3.5 122B A10B"
family = "qwen"
release_date = "2026-03-18"
last_updated = "2026-03-18"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.4
output = 3.2

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
