name = "Qwq 32B"
family = "qwen"
release_date = "2025-03-05"
last_updated = "2025-03-05"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = false
open_weights = true

[cost]
input = 0.66
output = 1

[limit]
context = 24_000
output = 24_000

[modalities]
input = ["text"]
output = ["text"]
