name = "DeepSeek v4 Pro"
family = "deepseek"
release_date = "2026-04-24"
last_updated = "2026-04-24"
attachment = true
reasoning = false
temperature = true
knowledge = "2026-01"
tool_call = true
open_weights = false

[cost]
input = 1.74
output = 3.48
cache_read= 0.14

[limit]
context = 128_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
