name = "Grok 4.1 Fast (Reasoning)"
family = "grok"
release_date = "2025-08-28"
last_updated = "2025-08-28"
attachment = false
reasoning = true
temperature = true
knowledge = "2023-10"
tool_call = true
open_weights = false

[cost]
input = 0.2
output = 1.5
cache_read = 0.02

[limit]
context = 256_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
