name = "Grok 4.1 Fast (Reasoning)"
family = "grok"
release_date = "2025-11-25"
last_updated = "2025-11-25"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-11"
tool_call = true
open_weights = false

[cost]
input = 0.2
output = 0.5
cache_read = 0.05

[limit]
context = 2_000_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
