name = "NVIDIA: Nemotron 3 Super"
release_date = "2026-03-11"
last_updated = "2026-04-11"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.1
output = 0.5
cache_read = 0.1

[limit]
context = 262144
output = 262144

[modalities]
input = ["text"]
output = ["text"]
