attachment = false
temperature = true
tool_call = true
structured_output = true

[extends]
from = "llama/llama-3.3-70b-instruct"

[cost]
input = 0.1
output = 0.32

[limit]
context = 131_072
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
