name = "Llama 3.2 3B Instruct"
family = "llama"
release_date = "2024-09-25"
last_updated = "2024-09-25"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = false
knowledge = "2023-12-31"
open_weights = true

[cost]
input = 0.0509
output = 0.335

[limit]
context = 80_000
output = 80_000

[modalities]
input = ["text"]
output = ["text"]
