name = "Llama Guard 4 12B"
family = "llama"
release_date = "2025-04-30"
last_updated = "2025-04-30"
attachment = true
reasoning = false
temperature = true
tool_call = false
structured_output = false
knowledge = "2024-08-31"
open_weights = true

[cost]
input = 0.18
output = 0.18

[limit]
context = 163_840
output = 16_384

[modalities]
input = ["image", "text"]
output = ["text"]
