name = "ElevenLabs Multilingual TTS v2"
family = "elevenlabs"
release_date = "2023-08-22"
last_updated = "2026-04-16"
attachment = false
reasoning = false
temperature = false
tool_call = false
open_weights = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["audio"]
