name = "Compound Mini"
family = "groq"
release_date = "2025-09-04"
last_updated = "2025-09-04"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-09-04"
tool_call = true
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
