temperature = true
tool_call = true
structured_output = true

[extends]
from = "google/gemini-2.5-flash"
omit = ["cost.input_audio"]

[cost]
input = 0.3
output = 2.5
reasoning = 2.5
cache_read = 0.03
cache_write = 0.083333

[limit]
context = 1_048_576
output = 65_535

[modalities]
input = ["pdf", "image", "text", "audio", "video"]
output = ["text"]
