temperature = true
tool_call = true
structured_output = true

[extends]
from = "google/gemini-2.5-flash-lite"
omit = ["cost.input_audio"]

[cost]
input = 0.1
output = 0.4
reasoning = 0.4
cache_read = 0.01
cache_write = 0.083333

[limit]
context = 1_048_576
output = 65_535

[modalities]
input = ["text", "image", "pdf", "audio", "video"]
output = ["text"]
