temperature = true
tool_call = true
structured_output = true

[extends]
from = "google/gemini-3.1-flash-lite-preview"
omit = ["cost.input_audio"]

[cost]
input = 0.25
output = 1.5
reasoning = 1.5
cache_read = 0.025
cache_write = 0.083333

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "video", "pdf", "audio"]
output = ["text"]
