temperature = true
tool_call = true
structured_output = true

[extends]
from = "google/gemini-3.1-pro-preview"

[interleaved]
field = "reasoning_details"

[cost]
input = 2
output = 12
reasoning = 12
cache_read = 0.2
cache_write = 0.375

[[cost.tiers]]
tier = { size = 200_000 }
input = 4
output = 18
cache_read = 0.4

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["audio", "pdf", "image", "text", "video"]
output = ["text"]
