name = "ChatGPT-4o-Latest"
family = "gpt"
release_date = "2024-08-14"
last_updated = "2024-08-14"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = true
status = "deprecated"

[cost]
input = 4.5
output = 14

[limit]
context = 128_000
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
