name = "GPT-Image-2"
release_date = "2026-04-21"
last_updated = "2026-04-21"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[cost]
input = 5.0505
output = 32.3232
cache_read = 1.2626

[limit]
context = 0
output = 0

[modalities]
input = ["text", "image"]
output = ["image"]
