name = "gpt-image-1.5"
release_date = "2025-12-16"
last_updated = "2025-12-16"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 128_000
output = 0

[modalities]
input = ["text", "image"]
output = ["image"]
