name = "GPT-4-Classic-0314"
family = "gpt"
release_date = "2024-08-26"
last_updated = "2024-08-26"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = true
status = "deprecated"

[cost]
input = 27
output = 54

[limit]
context = 8_192
output = 4_096

[modalities]
input = ["text", "image"]
output = ["text"]
