name = "Pro/moonshotai/Kimi-K2.5"
family = "kimi"
release_date = "2026-01-27"
last_updated = "2026-01-27"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[interleaved]
field = "reasoning_content"

[cost]
input = 0.45
output = 2.25
cache_input = 0.07

[limit]
context = 262_000
output = 262_000

[modalities]
input = ["text", "image"]
output = ["text"]
