name = "Qwen: Qwen3.5 Plus 2026-04-20"
release_date = "2026-04-27"
last_updated = "2026-05-01"
attachment = true
reasoning = true
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0.4
output = 2.4

[limit]
context = 1000000
output = 65536

[modalities]
input = ["text", "image", "video"]
output = ["text"]
