name = "E5 Large v2"
family = "text-embedding"
release_date = "2023-05-19"
last_updated = "2026-04-30"
attachment = false
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.02
output = 0.00

[limit]
context = 512
output = 1_024

[modalities]
input = ["text"]
output = ["text"]
