name = "o3-mini"
family = "o-mini"
release_date = "2024-12-20"
last_updated = "2025-01-29"
attachment = false
reasoning = true
temperature = false
tool_call = true
structured_output = true
knowledge = "2024-05"
open_weights = false

[cost]
input = 1.10
output = 4.40
cache_read = 0.55

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text"]
output = ["text"]
