name = "Wan2.2-T2V-A14B"
release_date = "2025-07-28"
last_updated = "2026-04-30"
attachment = false
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.60
output = 0.00

[limit]
context = 100
output = 1

[modalities]
input = ["text"]
output = ["video"]
