name = "DeepSeek V4 Flash"
family = "deepseek"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-04-23"
last_updated = "2026-04-24"
open_weights = true

[cost]
input = 0.14
output = 0.28
cache_read = 0.028

[limit]
context = 1_000_000
output = 384_000

[modalities]
input = ["text"]
output = ["text"]
