name = "Orpheus Arabic Saudi"
family = "canopylabs"
release_date = "2025-12-16"
last_updated = "2025-12-16"
attachment = false
reasoning = false
temperature = true
knowledge = "2025-12-16"
tool_call = false
open_weights = false

[cost]
input = 40.00
output = 0

[limit]
context = 4_000
output = 50_000

[modalities]
input = ["text"]
output = ["audio"]
