name = "MiniMax M2.7 Highspeed"
reasoning = true

[extends]
from = "minimax/MiniMax-M2.7-highspeed"

[interleaved]
field = "reasoning_content"

[cost]
input = 0.33
output = 1.32

[limit]
context = 100_000
output = 131_072
