name = "Hermes 4 405B"
family = "hermes"
release_date = "2025-08-26"
last_updated = "2025-08-26"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = false
knowledge = "2024-08-31"
open_weights = true

[cost]
input = 1
output = 3

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
