name = "DeepSeek-V4-Flash-EL"
attachment = true
reasoning = true
tool_call = true
release_date = "2026-04-24"
last_updated = "2026-05-02"
open_weights = true

[cost]
input = 0.14
output = 0.28

[limit]
context = 1_000_000
input = 1_000_000
output = 384_000

[modalities]
input = ["text"]
output = ["text"]