name = "xAI: Grok 4.20 Multi-Agent"
release_date = "2026-03-31"
last_updated = "2026-04-11"
attachment = true
reasoning = true
temperature = true
tool_call = false
open_weights = false

[cost]
input = 2
output = 6
cache_read = 0.2

[limit]
context = 2000000
output = 2000000

[modalities]
input = ["image", "pdf", "text"]
output = ["text"]
