name = "Perceptron: Perceptron Mk1"
release_date = "2026-05-12"
last_updated = "2026-05-16"
attachment = true
reasoning = true
tool_call = false
temperature = true
open_weights = false

[cost]
input = 0.15
output = 1.5

[limit]
context = 32768
output = 8192

[modalities]
input = ["image", "text", "video"]
output = ["text"]
