name = "Qwen: Qwen3.5-Flash"
family = "qwen"
release_date = "2026-02-25"
last_updated = "2026-02-25"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.065
output = 0.26

[limit]
context = 1_000_000
output = 65_536

[modalities]
input = ["text", "image", "video"]
output = ["text"]
