name = "Qwen3 VL 235B A22B Instruct"
family = "qwen"
release_date = "2025-09-23"
last_updated = "2025-09-23"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-03-31"
open_weights = true

[cost]
input = 0.2
output = 0.88
cache_read = 0.11

[limit]
context = 262_144
output = 16_384

[modalities]
input = ["text", "image"]
output = ["text"]
