name = "Qwen Plus 0728 (thinking)"
family = "qwen"
release_date = "2025-09-08"
last_updated = "2025-09-08"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-03-31"
open_weights = false

[cost]
input = 0.26
output = 0.78
cache_write = 0.325

[limit]
context = 1_000_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
