name = "Qwen2.5 VL 72B Instruct"
family = "qwen"
release_date = "2025-02-01"
last_updated = "2025-02-01"
attachment = true
reasoning = false
temperature = true
tool_call = false
structured_output = true
knowledge = "2024-06-30"
open_weights = true

[cost]
input = 0.25
output = 0.75

[limit]
context = 32_000
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
