name = "Qwen3 VL 8B Thinking"
family = "qwen"
release_date = "2025-10-14"
last_updated = "2025-10-14"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.117
output = 1.365

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["image", "text"]
output = ["text"]
