name = "Qwen3 Max"
family = "qwen"
release_date = "2025-09-23"
last_updated = "2025-09-23"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = false
knowledge = "2025-06-30"
open_weights = false

[cost]
input = 0.78
output = 3.9
cache_read = 0.156
cache_write = 0.975

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
