name = "Qwen3 14B"
family = "qwen"
release_date = "2025-04-28"
last_updated = "2025-04-28"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-03-31"
open_weights = true

[cost]
input = 0.1
output = 0.24

[limit]
context = 40_960
output = 40_960

[modalities]
input = ["text"]
output = ["text"]
