name = "Qwen3 235B A22B Thinking 2507"
family = "qwen"
release_date = "2025-07-25"
last_updated = "2025-07-25"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-06-30"
open_weights = true

[cost]
input = 0.1495
output = 1.495

[limit]
context = 131_072
output = 81_920

[modalities]
input = ["text"]
output = ["text"]
