name = "Qwen3 VL 30B A3B Thinking"
family = "qwen"
release_date = "2025-10-06"
last_updated = "2025-10-06"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-03-31"
open_weights = true

[cost]
input = 0.13
output = 1.56

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
