temperature = true
tool_call = false
structured_output = true

[extends]
from = "cohere/command-r7b-12-2024"

[cost]
input = 0.0375
output = 0.15

[limit]
context = 128_000
output = 4_000

[modalities]
input = ["text"]
output = ["text"]
