name = "Devstral Small 2 24B Instruct 2512"
family = "devstral"
release_date = "2025-12-09"
last_updated = "2025-12-09"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.12
output = 0.35

[limit]
context = 262_128
output = 262_128

[modalities]
input = ["text", "image"]
output = ["text"]
