name = "Interfaze Beta"
attachment = false
reasoning = true
tool_call = false
temperature = true
release_date = "2025-10-07"
last_updated = "2026-04-29"
open_weights = false

[cost]
input = 1.5
output = 3.5

[limit]
context = 1_000_000
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
