name = "Qwen3-VL 30B-A3B Instruct"
family = "qwen"
release_date = "2025-09-23"
last_updated = "2025-09-23"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.15
output = 0.55

[limit]
context = 256_000
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
