name = "Qwen3 30B-A3B Instruct 2507"
family = "qwen"
release_date = "2025-07-29"
last_updated = "2025-07-29"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.15
output = 0.55

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
