name = "DeepSeek V3.2"
family = "deepseek"
release_date = "2025-12-01"
last_updated = "2025-12-01"
knowledge = "2024-07"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = true

[cost]
input = 0.266
output = 0.444

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
