name = "DeepSeek R1 0528"
family = "deepseek-thinking"
release_date = "2025-05-28"
last_updated = "2025-05-28"
knowledge = "2024-07"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = true

[cost]
input = 0.585
output = 2.307

[limit]
context = 164_000
output = 164_000

[modalities]
input = ["text"]
output = ["text"]
