name = "Hermes 4 70B"
release_date = "2025-08-26"
last_updated = "2025-08-26"
knowledge = "2023-12"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = true

[cost]
input = 0.116
output = 0.358

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
