name = "Mistral Large 3 2512"
release_date = "2025-12-01"
last_updated = "2025-12-01"
knowledge = "2025-12"

[extends]
from = "mistral/mistral-large-2512"

[cost]
input = 0.5
output = 1.5
cache_read = 0.05

[limit]
context = 256_000
output = 256_000
