name = "Mixtral 8x7B Instruct v0.1"
release_date = "2023-12-11"
last_updated = "2023-12-11"
knowledge = "2023-09"
attachment = false
reasoning = true
tool_call = false
temperature = true
open_weights = true

[cost]
input = 0.438
output = 0.68

[limit]
context = 32_000
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
