name = "Qwen3.5 397B A17B"
release_date = "2026-02-16"
last_updated = "2026-02-16"
knowledge = "2026-01"
attachment = false

[extends]
from = "alibaba/qwen3.5-397b-a17b"
omit = ["structured_output"]

[limit]
context = 250_000
output = 250_000

[modalities]
input = ["text"]
output = ["text"]
