name = "Qwen3 Coder 30B A3B Instruct"
release_date = "2025-07-31"
last_updated = "2025-07-31"
reasoning = true

[extends]
from = "alibaba/qwen3-coder-30b-a3b-instruct"

[cost]
input = 0.053
output = 0.222

[limit]
context = 262_000
output = 262_000
