name = "Baidu: CoBuddy (free)"
release_date = "2026-05-06"
last_updated = "2026-05-07"
attachment = false
reasoning = true
temperature = false
tool_call = true
open_weights = false

[cost]
input = 0
output = 0

[limit]
context = 131072
output = 65536

[modalities]
input = ["text"]
output = ["text"]
