name = "Mistral Small 3.2 24B Instruct 2506"
family = "mistral-small"
release_date = "2025-10-01"
last_updated = "2025-10-01"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-09"
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.33
output = 0.33

[limit]
context = 32_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]