name = "Inflection 3 Pi"
release_date = "2024-10-11"
last_updated = "2024-10-11"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = false
knowledge = "2024-10-31"
open_weights = false

[cost]
input = 2.5
output = 10

[limit]
context = 8_000
output = 1_024

[modalities]
input = ["text"]
output = ["text"]
