name = "Anthropic: Claude Opus 4.6"
release_date = "2026-02-05"
last_updated = "2026-02-05"
attachment = true
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-05-31"
open_weights = false

[cost]
input = 5.0
output = 25.0
cache_read = 0.5
cache_write = 6.25

[limit]
context = 1000000
output = 128000

[modalities]
input = ["text", "image"]
output = ["text"]
