name = "Grok 4 Fast Reasoning"
family = "grok"
release_date = "2025-07-09"
last_updated = "2025-07-09"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.20
output = 0.50
cache_read = 0.05

[limit]
context = 2_000_000
output = 30_000

[modalities]
input = ["text", "image"]
output = ["text"]
