name = "Llama 4 Maverick 17B Instruct"
family = "llama"
release_date = "2025-04-05"
last_updated = "2025-04-05"
attachment = true
reasoning = false
temperature = true
tool_call = false
structured_output = false
open_weights = true

[cost]
input = 0.24
output = 0.97

[limit]
context = 8_192
output = 2_048

[modalities]
input = ["text", "image"]
output = ["text"]
