name = "Llama 3.2 11B Instruct"
family = "llama"
release_date = "2024-09-25"
last_updated = "2024-09-25"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = true
open_weights = true

[cost]
input = 0.07
output = 0.33

[limit]
context = 128_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
