name = "MiniMax M2.1 Lightning"
family = "minimax"
release_date = "2025-12-23"
last_updated = "2025-12-23"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = false
open_weights = true

[cost]
input = 0.12
output = 0.48

[limit]
context = 196_608
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
