name = "Qwen3 235B A22B FP8"
family = "qwen"
release_date = "2025-04-28"
last_updated = "2025-04-28"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.50
output = 2.50

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
