name = "inclusionAI: Ling-2.6-1T"
release_date = "2026-04-23"
last_updated = "2026-05-16"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0.3
output = 2.5
cache_read = 0.06

[limit]
context = 262144
output = 32768

[modalities]
input = ["text"]
output = ["text"]
