name = "Body Builder (beta)"
release_date = "2025-12-05"
last_updated = "2025-12-05"
attachment = false
reasoning = false
temperature = false
tool_call = false
structured_output = false
open_weights = false

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
