name = "GPT-5.2-Pro"
release_date = "2025-12-11"
last_updated = "2025-12-11"
attachment = true
reasoning = true
temperature = false
tool_call = true
knowledge = "2025-08-31"
open_weights = false

[cost]
input = 21.00
output = 168.00

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]

[provider]
npm = "@ai-sdk/openai"
api = "https://zenmux.ai/api/v1"
