name = "Cogito v2.1 671B"
family = "cogito"
release_date = "2025-11-13"
last_updated = "2025-11-13"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = true
open_weights = false

[cost]
input = 1.25
output = 1.25

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
