name = "DigitalOcean"
env = ["DIGITALOCEAN_ACCESS_TOKEN"]
npm = "@ai-sdk/openai-compatible"
api = "https://inference.do-ai.run/v1"
doc = "https://docs.digitalocean.com/products/gradient-ai-platform/details/models/"
