name = "Qwen3-Next-80B-A3B-Thinking-fast"
attachment = false
reasoning = true
tool_call = true
structured_output = true
temperature = true
knowledge = "2025-07"
release_date = "2025-07-25"
last_updated = "2026-05-07"
open_weights = true

[cost]
input = 0.15
output = 1.20
cache_read = 0.015
cache_write = 0.1875

[limit]
context = 8_000
input = 7_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
