name = "Claude 3.5 Haiku"
release_date = "2024-11-04"
last_updated = "2024-11-04"
attachment = true
reasoning = false
temperature = true
tool_call = true
knowledge = "2025-01-01"
open_weights = false

[cost]
input = 0.80
output = 4.00
cache_read = 0.08
cache_write = 1.00

[limit]
context = 200_000
output = 64_000

[modalities]
input = ["text", "image"]
output = ["text"]

[provider]
npm = "@ai-sdk/anthropic"
api = "https://zenmux.ai/api/anthropic/v1"
