name = "Claude-Sonnet-3.5-June"
family = "claude-sonnet"
release_date = "2024-11-18"
last_updated = "2024-11-18"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = true
status = "deprecated"

[cost]
input = 2.6
output = 13
cache_read = 0.26
cache_write = 3.2

[limit]
context = 189_096
output = 8_192

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
