name = "Mercury Coder Small Beta"
family = "mercury"
attachment = false
reasoning = false
tool_call = true
temperature = true
release_date = "2025-02-26"
last_updated = "2026-04-16"
open_weights = false

[cost]
input = 0.25
output = 1

[limit]
context = 32_000
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
