name = "Hunyuan A13B Instruct"
family = "hunyuan"
release_date = "2025-07-08"
last_updated = "2025-07-08"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = true
knowledge = "2025-03-31"
open_weights = true

[cost]
input = 0.14
output = 0.57

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
