name = "Hy3 preview"
family = "Hy"
release_date = "2026-04-22"
last_updated = "2026-04-22"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = false
open_weights = true

[cost]
input = 0.066
output = 0.26
cache_read = 0.029

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
