name = "Llama 3 8B Instruct Awq"
family = "llama"
release_date = "2024-05-09"
last_updated = "2024-05-09"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = false
open_weights = true

[cost]
input = 0.123
output = 0.266

[limit]
context = 8_192
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
