name = "Claude Opus Latest"
family = "claude-opus"
release_date = "2026-04-21"
last_updated = "2026-04-21"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 5
output = 25
cache_read = 0.5
cache_write = 6.25

[limit]
context = 1_000_000
output = 128_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
