name = "Anthropic Claude Haiku Latest"
family = "claude-haiku"
release_date = "2026-04-27"
last_updated = "2026-04-27"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1
output = 5
cache_read = 0.1
cache_write = 1.25

[limit]
context = 200_000
output = 64_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
