name = "Kimi K2 Instruct"
family = "kimi"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
knowledge = "2024-04"
release_date = "2026-01-27"
last_updated = "2026-01-27"

[cost]
input = 0.55
output = 2.75

[limit]
context = 254_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]