# https://deepinfra.com/zai-org/GLM-5.1
name = "GLM-5.1"
family = "glm"
release_date = "2026-04-07"
last_updated = "2026-04-07"
knowledge = "2025-04"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true
structured_output = true

[interleaved]
field = "reasoning_content"

[cost]
input = 1.4
output = 4.4
cache_read = 0.26

[limit]
context = 202_752 
# https://deepinfra.com/docs/advanced/max_tokens_limit
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
