name = "Kimi-K2.5"
family = "kimi"
release_date = "2026-01-27"
last_updated = "2026-01-27"
attachment = true
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-01"
open_weights = true

[interleaved]
field = "reasoning_content"

[cost]
input = 0
output = 0
cache_read = 0
cache_write = 0

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text", "image", "video"]
output = ["text"]
