name = "Magistral Small 2506"
release_date = "2025-09-25"
last_updated = "2025-09-25"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 32_768
input = 32_768
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
