name = "Mistral Medium 3"
family = "mistral-medium"
release_date = "2025-09-25"
last_updated = "2025-09-25"
attachment = true
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 131_072
input = 131_072
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
