name = "Mistral: Mixtral 8x7B Instruct"
release_date = "2023-12-10"
last_updated = "2026-03-15"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 32_768
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
