name = "Morph V3 Large"
family = "morph"
release_date = "2025-07-07"
last_updated = "2025-07-07"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.9
output = 1.9

[limit]
context = 262_144
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
