name = "GLM 4.7"
release_date = "2025-12-23"
last_updated = "2025-12-23"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-01-01"
open_weights = false

[cost]
input = 0.28
output = 1.14
cache_read = 0.06

[limit]
context = 200_000
output = 64_000

[interleaved]
field = "reasoning_content"

[modalities]
input = ["text"]
output = ["text"]
