name = "GPT OSS 20B"
family = "gpt-oss"
release_date = "2025-08-05"
last_updated = "2025-08-05"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.03
output = 0.16

[limit]
context = 16_368
output = 16_368

[modalities]
input = ["text"]
output = ["text"]
