name = "Kat Coder Pro V2"
family = "kat-coder"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-03-27"
last_updated = "2026-03-30"
open_weights = false

[cost]
input = 0.3
output = 1.2
cache_read = 0.06

[limit]
context = 256_000
output = 256_000

[modalities]
input = ["text"]
output = ["text"]
