name = "Grok Imagine Image Quality"
family = "grok"
release_date = "2026-04-03"
last_updated = "2026-04-03"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = false

[limit]
context = 8_000
output = 0

[modalities]
input = ["text", "image", "pdf"]
output = ["image", "pdf"]
