name = "Claude Opus 4.5"
family = "claude-opus"
attachment = true
reasoning = true
tool_call = true
structured_output = true
temperature = true
release_date = "2025-12-06"
last_updated = "2026-04-12"
open_weights = false

[cost]
input = 6
output = 30
cache_read = 0.6
cache_write = 7.5

[limit]
context = 198_000
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
