name = "MiniMax M2.5"
family = "minimax"
attachment = false
reasoning = true
tool_call = true
temperature = true
release_date = "2026-02-12"
last_updated = "2026-04-12"
open_weights = false

[interleaved]
field = "reasoning_content"

[cost]
input = 0.34
output = 1.19
cache_read = 0.04

[limit]
context = 198_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
