name = "OpenAI GPT OSS 120B"
family = "gpt-oss"
attachment = false
reasoning = true
tool_call = true
temperature = true
knowledge = "2025-07"
release_date = "2025-11-06"
last_updated = "2026-05-06"
open_weights = true

[cost]
input = 0.07
output = 0.3

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
