name = "GLM 4.6"
family = "glm"
attachment = false
reasoning = true
tool_call = true
structured_output = true
temperature = true
release_date = "2024-04-01"
last_updated = "2026-04-04"
open_weights = true

[interleaved]
field = "reasoning_content"

[cost]
input = 0.85
output = 2.75
cache_read = 0.3

[limit]
context = 198_000
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
