name = "Llama 3.2 3B Instruct"
family = "llama"
release_date = "2024-09-18"
last_updated = "2024-09-18"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = true

[cost]
input = 0.03
output = 0.05

[limit]
context = 32_768
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
