name = "Mistral Small 3.1 24B"
family = "mistral-small"
release_date = "2025-03-17"
last_updated = "2025-03-17"
attachment = true
reasoning = false
temperature = true
tool_call = false
structured_output = false
knowledge = "2023-10-31"
open_weights = true

[cost]
input = 0.351
output = 0.555

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
