name = "Mistral Large"
family = "mistral-large"
release_date = "2024-02-26"
last_updated = "2024-02-26"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2024-11-30"
open_weights = false

[cost]
input = 2
output = 6
cache_read = 0.2

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text", "pdf"]
output = ["text"]
