name = "Saba"
family = "mistral"
release_date = "2025-02-17"
last_updated = "2025-02-17"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2024-09-30"
open_weights = false

[cost]
input = 0.2
output = 0.6
cache_read = 0.02

[limit]
context = 32_768
output = 32_768

[modalities]
input = ["text", "pdf"]
output = ["text"]
