name = "Mistral Medium 3"
family = "mistral-medium"
release_date = "2025-05-07"
last_updated = "2025-05-07"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-03-31"
open_weights = false

[cost]
input = 0.4
output = 2
cache_read = 0.04

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
