name = "Pixtral Large 2411"
family = "mistral"
release_date = "2024-11-19"
last_updated = "2024-11-19"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2024-07-31"
open_weights = false

[cost]
input = 2
output = 6
cache_read = 0.2

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
