temperature = true
tool_call = true
structured_output = false

[extends]
from = "zai/glm-4.6v"

[cost]
input = 0.3
output = 0.9
cache_read = 0.05

[limit]
context = 131_072
output = 24_000

[modalities]
input = ["image", "text", "video"]
output = ["text"]
