temperature = true
tool_call = true
structured_output = true

[extends]
from = "zai/glm-4.6"
omit = ["cost.cache_write"]

[cost]
input = 0.43
output = 1.74
cache_read = 0.08

[limit]
context = 202_752
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
