temperature = true
tool_call = true
structured_output = false

[extends]
from = "zai/glm-4.5v"

[cost]
input = 0.6
output = 1.8
cache_read = 0.11

[limit]
context = 65_536
output = 16_384

[modalities]
input = ["text", "image"]
output = ["text"]
