name = "ByteDance Seed: Dola Seed 2.0 Pro (free)"
release_date = "2025-08-26"
last_updated = "2026-04-11"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0
output = 0

[limit]
context = 256000
output = 128000

[modalities]
input = ["image", "text"]
output = ["text"]
