name = "Phi 4"
family = "phi"
release_date = "2025-01-10"
last_updated = "2025-01-10"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = true
knowledge = "2024-06-30"
open_weights = true

[cost]
input = 0.065
output = 0.14

[limit]
context = 16_384
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
