name = "Kimi K2.5 Turbo (firepass)"
family = "kimi-thinking"
release_date = "2026-01-27"
last_updated = "2026-01-27"
knowledge = "2025-01"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
cache_read = 0
input = 0
output = 0

[limit]
context = 256_000
output = 256_000

[modalities]
input = ["text", "image"]
output = ["text"]

[interleaved]
field = "reasoning_content"
