name = "glm-5v-turbo"
family = "glm"
release_date = "2026-04-01"
last_updated = "2026-04-01"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = false

[interleaved]
field = "reasoning_content"

[cost]
input = 0
output = 0
cache_read = 0
cache_write = 0

[limit]
context = 200000
output = 131072

[modalities]
input = ["text", "image", "video", "pdf"]
output = ["text"]
