name = "llama-3.3-70b-cs"
release_date = "2025-05-13"
last_updated = "2025-05-13"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
status = "deprecated"

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
