name = "Google: Lyria 3 Pro Preview"
release_date = "2026-03-30"
last_updated = "2026-04-11"
attachment = true
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 0
output = 0

[limit]
context = 1048576
output = 65536

[modalities]
input = ["image", "text"]
output = ["audio", "text"]
