name = "MiMo-V2-TTS"
family = "mimo"
release_date = "2026-03-18"
last_updated = "2026-03-18"
attachment = false
reasoning = false
tool_call = false
open_weights = true

[cost]
input = 0
output = 0

[limit]
context = 8_000
output = 16_000

[modalities]
input = ["text"]
output = ["audio"]
