name = "MiMo-V2.5-TTS-VoiceClone"
family = "mimo"
release_date = "2026-04-22"
last_updated = "2026-04-22"
attachment = false
reasoning = false
tool_call = false
open_weights = true

[cost]
input = 0
output = 0

[limit]
context = 8_192
output = 8_192

[modalities]
input = ["text"]
output = ["audio"]
