name = "Aion-1.0-Mini"
release_date = "2025-02-04"
last_updated = "2025-02-04"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = false
open_weights = true

[cost]
input = 0.7
output = 1.4

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
