name = "Aion-1.0"
release_date = "2025-02-04"
last_updated = "2025-02-04"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 4
output = 8

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
