name = "Grok 4.3"
family = "grok"
attachment = true
reasoning = true
tool_call = true
temperature = true
release_date = "2026-04-30"
last_updated = "2026-05-01"
open_weights = false

[cost]
input = 1.25
output = 2.5
cache_read = 0.19999999999999998

[limit]
context = 1_000_000
output = 1_000_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
