name = "Z.ai: GLM 5V Turbo"
release_date = "2026-04-01"
last_updated = "2026-04-11"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 1.2
output = 4
cache_read = 0.24

[limit]
context = 202752
output = 131072

[modalities]
input = ["image", "text", "video"]
output = ["text"]
