name = "Tencent: Hy3 Preview"
release_date = "2026-04-22"
last_updated = "2026-05-16"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0.066
output = 0.26
cache_read = 0.029

[limit]
context = 262144
output = 262144

[modalities]
input = ["text"]
output = ["text"]
