name = "chatgpt-image-latest"
family = "gpt-image"
attachment = true
tool_call = false
reasoning = false 
temperature = false
open_weights = false
release_date = "2025-12-16" 
last_updated = "2025-12-16" 

[limit]
context = 0
input = 0
output = 0


[modalities]
input = ["text", "image"]
output = ["text", "image"]
