name = "GPT-4.1 mini"
family = "gpt-mini"
release_date = "2025-04-14"
last_updated = "2025-04-14"
attachment = true
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.40
output = 1.60
cache_read = 0.10

[limit]
context = 1047576
output = 32768

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
