name = "GPT-4.1 nano"
family = "gpt-nano"
release_date = "2025-04-14"
last_updated = "2025-04-14"
attachment = true
reasoning = false
temperature = true
knowledge = "2024-04"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.10
output = 0.40
cache_read = 0.025

[limit]
context = 1047576
output = 32768

[modalities]
input = ["text", "image"]
output = ["text"]
