name = "gpt-image-1.5"
family = "gpt-image"
attachment = true
tool_call = false
reasoning = false 
temperature = false         
release_date = "2025-11-25" 
last_updated = "2025-11-25" 
open_weights = false

[limit]
context = 0
input = 0
output = 0

[modalities]
input = ["text", "image"]
output = ["text", "image"]
