name = "GPT-5 Chat (latest)"
family = "gpt-codex"
release_date = "2025-08-07"
last_updated = "2025-08-07"
attachment = true
reasoning = true
temperature = true
knowledge = "2024-09-30"
tool_call = false
structured_output = true
open_weights = false

[cost]
input = 1.25
output = 10.00
cache_read = 0.125

[limit]
context = 400_000
input = 272_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
