name = "minimax-m2.7"
family = "minimax"
attachment = false
reasoning = true
tool_call = true
release_date = "2026-03-18"
last_updated = "2026-03-18"
open_weights = true

[limit]
context = 196608
output = 196608

[modalities]
input = ["text"]
output = ["text"]
