name = "OpenAI: GPT Mini Latest"
release_date = "2026-04-27"
last_updated = "2026-05-01"
attachment = true
reasoning = true
tool_call = true
temperature = false
open_weights = false

[cost]
input = 0.75
output = 4.5
cache_read = 0.075

[limit]
context = 400000
output = 128000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
