name = "L3 8B Stheno V3.2"
family = "llama"
release_date = "2024-11-29"
last_updated = "2024-11-29"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.05
output = 0.05

[limit]
context = 8_192
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
