name = "Mistral: Mistral Small 4"
release_date = "2026-03-16"
last_updated = "2026-04-11"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.15
output = 0.6
cache_read = 0.015

[limit]
context = 262144
output = 262144

[modalities]
input = ["image", "text"]
output = ["text"]
