name = "cosmos-predict1-5b"
release_date = "2025-03-18"
last_updated = "2025-03-18"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 0
output = 4_096

[modalities]
input = ["text", "image", "video"]
output = ["video"]
