name = "cosmos-transfer2.5-2b"
release_date = "2026-02-26"
last_updated = "2026-02-26"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 0
output = 4_096

[modalities]
input = ["text", "image", "video"]
output = ["video"]
