name = "Llama 3.3 Nemotron Super 49B v1.5"
family = "nemotron"
release_date = "2025-07-25"
last_updated = "2025-07-25"
attachment = false
reasoning = true
temperature = true
knowledge = "2023-12"
tool_call = true
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
