name = "llama-nemotron-rerank-vl-1b-v2"
release_date = "2026-03-31"
last_updated = "2026-03-31"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text", "image"]
output = ["text"]
