name = "llama-3.1-nemotron-safety-guard-8b-v3"
release_date = "2025-10-28"
last_updated = "2025-10-28"
attachment = false
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
