name = "llama-3_2-nemoretriever-300m-embed-v1"
release_date = "2025-07-24"
last_updated = "2025-07-24"
attachment = false
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 32_768
output = 2_048

[modalities]
input = ["text"]
output = ["text"]
