name = "nv-embedcode-7b-v1"
release_date = "2025-03-17"
last_updated = "2025-05-29"
attachment = false
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 32_768
output = 2_048

[modalities]
input = ["text"]
output = ["text"]
