name = "Qwen3.5 397B Fast"
family = "qwen"
release_date = "2026-02-01"
last_updated = "2026-02-01"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.69
output = 4.14

[limit]
context = 262_128
output = 262_128

[modalities]
input = ["text"]
output = ["text"]
