name = "Deepseek R1 Distill Qwen 32B"
family = "deepseek"
release_date = "2025-01-22"
last_updated = "2025-01-22"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = false
open_weights = true

[cost]
input = 0.497
output = 4.881

[limit]
context = 80_000
output = 80_000

[modalities]
input = ["text"]
output = ["text"]
