name = "Volcengine Coding Plan"
env = ["VOLCENGINE_CODING_PLAN_API_KEY"]
npm = "@ai-sdk/openai-compatible"
doc = "https://www.volcengine.com/docs/82379/1928261?lang=zh"
api = "https://ark.cn-beijing.volces.com/api/coding/v3"
