name = "Reka Edge"
release_date = "2026-03-20"
last_updated = "2026-04-11"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.1
output = 0.1

[limit]
context = 16384
output = 16384

[modalities]
input = ["image", "text", "video"]
output = ["text"]
