name = "MiniMax M1"
family = "minimax"
release_date = "2025-06-17"
last_updated = "2025-06-17"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = false
knowledge = "2024-06-30"
open_weights = false

[cost]
input = 0.4
output = 2.2

[limit]
context = 1_000_000
output = 40_000

[modalities]
input = ["text"]
output = ["text"]
