temperature = true
tool_call = true
structured_output = true

[extends]
from = "minimax/MiniMax-M2.5"
omit = ["cost.cache_read", "cost.cache_write"]

[interleaved]
field = "reasoning_details"

[cost]
input = 0.15
output = 1.15

[limit]
context = 196_608
output = 196_608

[modalities]
input = ["text"]
output = ["text"]
