name = "DeepSeek-V3.2"
family = "deepseek"
release_date = "2026-02-06"
last_updated = "2026-02-06"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-07"
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.62
output = 1.85

[limit]
context = 163_840
output = 81_920

[modalities]
input = ["text"]
output = ["text"]
