name = "DeepSeek-V3.1"
family = "deepseek"
release_date = "2025-09-18"
last_updated = "2025-09-18"
attachment = false
reasoning = true
temperature = true
knowledge = "2024-07"
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.58
output = 1.68

[limit]
context = 163_840
output = 81_920

[modalities]
input = ["text"]
output = ["text"]
