name = "Google Gemma 3 12B"
family = "gemma"
release_date = "2024-12-01"
last_updated = "2024-12-01"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = true
knowledge = "2024-12"
open_weights = false

[cost]
input = 0.049999999999999996
output = 0.09999999999999999

[limit]
context = 131072
output = 8192

[modalities]
input = ["text", "image"]
output = ["text"]
