name = "Magistral Small 1.2"
family = "magistral"
release_date = "2025-12-02"
last_updated = "2025-12-02"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.50
output = 1.50

[limit]
context = 128_000
output = 40_000

[modalities]
input = ["text", "image"]
output = ["text"]
