name = "GPT OSS Safeguard 20B"
family = "gpt-oss"
release_date = "2024-12-01"
last_updated = "2024-12-01"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.07
output = 0.20

[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
