name = "OpenAI GPT Mini Latest"
family = "gpt-mini"
release_date = "2026-04-27"
last_updated = "2026-04-27"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = true
knowledge = "2025-08-31"
open_weights = false

[cost]
input = 0.75
output = 4.5
cache_read = 0.075

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["pdf", "image", "text"]
output = ["text"]
