name = "Qwen3.5-122B-A10B"
family = "qwen"
release_date = "2026-02-26"
last_updated = "2026-02-26"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.4
output = 3.2

[limit]
context = 262_144
output = 65_536

[modalities]
input = ["text", "image", "video"]
output = ["text"]
