name = "DeepSeek-V3.2"
release_date = "2025-12-01"
last_updated = "2025-12-01"
attachment = true
reasoning = true
temperature = true
open_weights = true
tool_call = true

[cost]
input = 0.27
output = 0.4
cache_read = 0.13

[limit]
context = 128_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
