name = "glm-4.7"
release_date = "2025-12-22"
last_updated = "2025-12-22"
attachment = true
reasoning = true
temperature = true
open_weights = false
tool_call = true
status = "deprecated"

[limit]
context = 205_000
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
