name = "Kimi-K2.5"
release_date = "2026-01-27"
last_updated = "2026-01-27"
attachment = true
reasoning = true
temperature = true
open_weights = false
tool_call = true

[cost]
input = 0.6
output = 3
cache_read = 0.1

[limit]
context = 128_000
output = 262_144

[modalities]
input = ["text", "image", "video"]
output = ["text"]
