name = "Gemini-3-Pro"
family = "gemini-pro"
release_date = "2025-10-22"
last_updated = "2025-10-22"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true
status = "deprecated"

[cost]
input = 1.6
output = 9.6
cache_read = 0.16

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "video", "audio"]
output = ["text"]
