name = "ERNIE 4.5 VL 424B A47B "
family = "ernie"
release_date = "2025-06-30"
last_updated = "2025-06-30"
attachment = true
reasoning = true
temperature = true
tool_call = false
structured_output = false
knowledge = "2025-03-31"
open_weights = true

[cost]
input = 0.42
output = 1.25

[limit]
context = 123_000
output = 16_000

[modalities]
input = ["image", "text"]
output = ["text"]
