name = "gemini-2.5-flash-lite"
family = "gemini-flash-lite"
release_date = "2025-06-17"
last_updated = "2025-06-17"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-01"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.10
output = 0.40
cache_read = 0.01
input_audio = 0.30

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "audio", "video", "pdf"]
output = ["text"]
