name = "gpt-5-mini"
family = "gpt-mini"
release_date = "2025-08-07"
last_updated = "2025-08-07"
attachment = true
reasoning = true
temperature = false
knowledge = "2024-05-30"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.25
output = 2.00
cache_read = 0.025

[limit]
context = 400_000
input = 272_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
