name = "gpt-5.4"
family = "gpt"
release_date = "2026-04-27"
last_updated = "2026-04-27"
attachment = true
reasoning = true
temperature = false
knowledge = "2025-08-31"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 2.50
output = 15.00
cache_read = 0.25

[limit]
context = 1_050_000
input = 922_000
output = 128_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
