temperature = true
tool_call = true
structured_output = false

[extends]
from = "xiaomi/mimo-v2-flash"

[interleaved]
field = "reasoning_details"

[cost]
input = 0.1
output = 0.3
cache_read = 0.01

[limit]
context = 262_144
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
