name = "Mistral Small 3.2 24B Instruct (2506)"

last_updated = "2026-03-17"

[extends]
from = "mistral/mistral-small-2506"

[cost]
input = 0.15
output = 0.35

[limit]
context = 128_000
output = 32_768
