name = "Qwen3.5 397B A17B"

release_date = "2026-03-17"
last_updated = "2026-03-17"
knowledge = "2025-04"

[extends]
from = "alibaba/qwen3.5-397b-a17b"

[cost]
input = 0.60
output = 3.60

[limit]
context = 256_000
output = 16_384

[modalities]
input = ["text", "image", "video"]
output = ["text"]
