name = "Nova Pro 1.0"
family = "nova-pro"
release_date = "2024-12-05"
last_updated = "2024-12-05"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = false
knowledge = "2024-10-31"
open_weights = false

[cost]
input = 0.8
output = 3.2

[limit]
context = 300_000
output = 5_120

[modalities]
input = ["text", "image"]
output = ["text"]
