name = "KAT-Coder-Pro-V2"
release_date = "2026-03-30"
last_updated = "2026-03-30"
attachment = false
reasoning = false
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.30
output = 1.20
cache_read = 0.06

[limit]
context = 256_000
output = 80_000

[modalities]
input = ["text"]
output = ["text"]
