name = "Google: Gemini Flash Latest"
release_date = "2026-04-27"
last_updated = "2026-05-01"
attachment = true
reasoning = true
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0.5
output = 3.0
cache_read = 0.05
cache_write = 0.08333333333333334

[limit]
context = 1048576
output = 65536

[modalities]
input = ["text", "image", "audio", "video", "pdf"]
output = ["text"]
