name = "DeepSeek V3.1"
family = "deepseek"
release_date = "2025-08-21"
last_updated = "2025-08-21"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-03-31"
open_weights = true

[cost]
input = 0.21
output = 0.79
cache_read = 0.13

[limit]
context = 163_840
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
