name = "FLUX.1-schnell"
release_date = "2024-08-01"
last_updated = "2026-02-04"
attachment = false
reasoning = false
temperature = false
knowledge = "2024-07"
tool_call = false
structured_output = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 77
input = 77
output = 0

[modalities]
input = ["text"]
output = ["image"]
