name = "FLUX.1-Kontext-dev"
release_date = "2025-08-12"
last_updated = "2025-08-12"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 40_960
output = 40_960

[modalities]
input = ["text", "image"]
output = ["image"]
