name = "MiniMax M2.7"
release_date = "2026-03-20"
last_updated = "2026-03-20"
attachment = true
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-01-01"
open_weights = false

[cost]
input = 0.3055
output = 1.2219

[limit]
context = 204_800
output = 131_070

[modalities]
input = ["text"]
output = ["text"]

[provider]
npm = "@ai-sdk/anthropic"
api = "https://zenmux.ai/api/anthropic/v1"
