name = "Whisper Large v3 Turbo"
family = "whisper"
release_date = "2024-10-01"
last_updated = "2024-10-01"
attachment = false
reasoning = false
temperature = true
knowledge = "2024-10"
tool_call = false
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 448
output = 448

[modalities]
input = ["audio"]
output = ["text"]
