name = "Gemini Embedding 001"
family = "gemini"
release_date = "2025-05-20"
last_updated = "2025-05-20"
attachment = false
reasoning = false
temperature = false
tool_call = false
knowledge = "2025-05"
open_weights = false

[cost]
input = 0.15
output = 0

[limit]
context = 2_048
output = 1

[modalities]
input = ["text"]
output = ["text"]
