name = "Gemini 2.0 Flash-Lite"
family = "gemini-flash-lite"
release_date = "2024-12-11"
last_updated = "2024-12-11"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2024-06"
open_weights = false

[cost]
input = 0.075
output = 0.3

[limit]
context = 1_048_576
output = 8_192

[modalities]
input = ["text", "image", "audio", "video", "pdf"]
output = ["text"]
