name = "Gemini 2.5 Flash-Lite"
family = "gemini-flash-lite"
release_date = "2025-06-17"
last_updated = "2025-06-17"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
knowledge = "2025-01"
open_weights = false

[cost]
input = 0.1
output = 0.4
cache_read = 0.01
input_audio = 0.3

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "audio", "video", "pdf"]
output = ["text"]
