name = "Gemma 3n 2B"
family = "gemma"
release_date = "2025-07-09"
last_updated = "2025-07-09"
attachment = true
reasoning = false
temperature = true
knowledge = "2024-10"
tool_call = false
open_weights = true

[cost]
input = 0
output = 0

[limit]
context = 8_192
output = 2_000

[modalities]
input = ["text"]
output = ["text"]
