name = "GMI Cloud"
env = ["GMICLOUD_API_KEY"]
npm = "@ai-sdk/openai-compatible"
api = "https://api.gmi-serving.com/v1"
doc = "https://docs.gmicloud.ai/inference-engine/api-reference/llm-api-reference"
