name = "GLM-5"
family = "glm"
attachment = false
reasoning = true
tool_call = true
structured_output = true
temperature = true
release_date = "2026-02-12"
last_updated = "2026-02-12"
open_weights = true

[interleaved]
field = "reasoning_content"

[cost]
input = 1
output = 3.2

[limit]
context = 202_752
output = 202_752

[modalities]
input = ["text"]
output = ["text"]
