temperature = true
tool_call = true
structured_output = true

[extends]
from = "openai/gpt-4o"
omit = ["cost.cache_read"]

[cost]
input = 2.5
output = 10

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
