name = "GPT-3.5 Turbo Instruct"
family = "gpt"
release_date = "2023-09-28"
last_updated = "2023-09-28"
attachment = false
reasoning = false
temperature = true
tool_call = false
structured_output = true
knowledge = "2021-09-30"
open_weights = false

[cost]
input = 1.5
output = 2

[limit]
context = 4_095
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
