name = "GPT-5 Image"
family = "gpt"
release_date = "2025-10-14"
last_updated = "2025-10-14"
attachment = true
reasoning = true
temperature = true
tool_call = false
structured_output = true
knowledge = "2024-10-01"
open_weights = false

[cost]
input = 10
output = 10
cache_read = 1.25

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["image", "text", "pdf"]
output = ["image", "text"]
