name = "GPT-5 Chat"
family = "gpt-codex"
release_date = "2025-08-07"
last_updated = "2025-08-07"
attachment = true
reasoning = false
temperature = false
tool_call = false
structured_output = true
knowledge = "2024-09-30"
open_weights = false

[cost]
input = 1.25
output = 10
cache_read = 0.125

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["pdf", "image", "text"]
output = ["text"]
