name = "GPT-4 (older v0314)"
family = "gpt"
release_date = "2023-05-28"
last_updated = "2023-05-28"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2021-09-30"
open_weights = false

[cost]
input = 30
output = 60

[limit]
context = 8_191
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
