name = "GPT-5.1 Chat"
family = "gpt-codex"
release_date = "2025-11-13"
last_updated = "2025-11-13"
attachment = true
reasoning = false
temperature = false
tool_call = true
structured_output = true
knowledge = "2024-09-30"
open_weights = false

[cost]
input = 1.25
output = 10
cache_read = 0.13

[limit]
context = 128_000
output = 32_000

[modalities]
input = ["pdf", "image", "text"]
output = ["text"]
