temperature = false
tool_call = true
structured_output = true

[extends]
from = "openai/gpt-5.2-codex"
omit = ["limit.input"]

[cost]
input = 1.75
output = 14
cache_read = 0.175

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
