name = "GPT-3.5 Turbo (older v0613)"
family = "gpt"
release_date = "2024-01-25"
last_updated = "2024-01-25"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2021-09-30"
open_weights = false

[cost]
input = 1
output = 2

[limit]
context = 4_095
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
