temperature = true
tool_call = true
structured_output = true

[extends]
from = "openai/gpt-4o-2024-05-13"

[cost]
input = 5
output = 15

[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
