temperature = false
tool_call = true
structured_output = true

[extends]
from = "openai/gpt-5.1-codex-mini"
omit = ["limit.input"]

[cost]
input = 0.25
output = 2
cache_read = 0.025

[limit]
context = 400_000
output = 100_000

[modalities]
input = ["image", "text"]
output = ["text"]
