temperature = false
tool_call = true
structured_output = true

[extends]
from = "openai/gpt-5.4-mini"
omit = ["experimental", "limit.input"]

[cost]
input = 0.75
output = 4.5
cache_read = 0.075

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["pdf", "image", "text"]
output = ["text"]
