temperature = true
tool_call = true
structured_output = true

[extends]
from = "openai/gpt-4.1"

[cost]
input = 2
output = 8
cache_read = 0.5

[limit]
context = 1_047_576
output = 32_768

[modalities]
input = ["image", "text", "pdf"]
output = ["text"]
