name = "GPT Audio Mini"
family = "o-mini"
release_date = "2026-01-19"
last_updated = "2026-01-19"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.6
output = 2.4

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text", "audio"]
output = ["text", "audio"]
