name = "gpt-oss-120b"
family = "gpt-oss"
release_date = "2025-08-05"
last_updated = "2025-08-05"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
knowledge = "2024-06-30"
open_weights = true

[cost]
input = 0.039
output = 0.18

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
