temperature = false
tool_call = false
structured_output = true

[extends]
from = "openai/o1-pro"

[cost]
input = 150
output = 600

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
