name = "o3 Mini High"
family = "o"
release_date = "2025-02-12"
last_updated = "2025-02-12"
attachment = true
reasoning = true
temperature = false
tool_call = true
structured_output = true
knowledge = "2023-10-31"
open_weights = false

[cost]
input = 1.1
output = 4.4
cache_read = 0.55

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text", "pdf"]
output = ["text"]
