name = "Hy3 preview"
family = "Hy"
release_date = "2026-04-20"
last_updated = "2026-04-20"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = true

[cost]
input = 0
output = 0
cache_read = 0
cache_write = 0

[limit]
context = 256000
output = 64000

[modalities]
input = ["text"]
output = ["text"]
