name = "Llama 3.1 8B Instruct"
family = "llama"
release_date = "2025-01-01"
last_updated = "2025-01-01"
attachment = false
reasoning = false
temperature = true
knowledge = "2023-12"
tool_call = true
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 16_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
